### ISSUE TITLE
Adjust CSS code that shows font-variation-settings

### ISSUE THREAD

**Issue by arrowtype** [arrowtype/recursive-specimen#1]
I mentioned that we would need to do the CSS code for the font-variation-settings in a slightly different way. Here's an example closer to how it should probably be:

https://codepen.io/thundernixon/pen/KjeQyV?editors=1100

That is, it might look something like this:

```CSS
.tester input {
  font-variation-settings: var(--w), var(--s), var(--i), var(--x);
  --w: "wght" 400; /* Weight: controls the overall thickness and density of letters. 300 to 900 */
  --s: "slnt" 0; /* Slant: controls the angle of the letters. 0 to -15 */
  --i: "ital" 0; / * Italic: controls whether lowercase letters have Roman or Cursive letterforms. 0 to 1 */
  --x: "XPRN" 1; /* Expression: controls whether letters are Linear (normal) or Casual (fun). 0 to 1.  */
}
```
